# -*- coding: utf-8 -*-
"""Code challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cfi3JpAy4eeok6qhw_CIfBg5HeVjH7b3
"""



import pandas as pd

# Create a small sample dataset
data = {'col1': [1, 2, 3, 4, 5],
        'col2': [10, 20, 30, 40, 50],
        'col3': ['A', 'B', 'C', 'D', 'E']}
df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:")
display(df)

import matplotlib.pyplot as plt
import numpy as np

# Create a simple list of numbers
data_to_plot = [1, 4, 2, 7, 5, 9, 3, 6, 8, 10]

# Plot the data
plt.figure(figsize=(10, 6))
plt.plot(data_to_plot)
plt.title("Simple Line Graph")
plt.xlabel("Index")
plt.ylabel("Value")
plt.grid(True)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %pip install requests

import requests

# Example public API (using the JSONPlaceholder API)
api_url = "https://jsonplaceholder.typicode.com/posts/1"

try:
    # Fetch data from the API
    response = requests.get(api_url)
    response.raise_for_status()  # Raise an exception for bad status codes

    # Parse the JSON response
    data = response.json()

    # Print a key piece of information (e.g., the title of the post)
    print("Title of the post:", data.get('title'))

except requests.exceptions.RequestException as e:
    print(f"Error fetching data from the API: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

# Display summary statistics
print("\nSummary Statistics:")
display(df.describe())

import numpy as np

# Create a NumPy array of numbers from 1 to 10
arr = np.arange(1, 11)

# Calculate the mean of the array
mean_value = np.mean(arr)

# Display the array and its mean
print("NumPy array:", arr)
print("Mean of the array:", mean_value)